### ISSUE TITLE
Transfer the Component decorator

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/reduct#1]
As discussed yesterday, this repository should contain the glue-code for the future framework.

As the first step, we should transfer the component decorator of yours into this repo.
https://github.com/akoenig/lightfold

**Comment by akoenig** [comment]
As far as I remember, we discussed porting the decorators over from [lightfold](https://github.com/akoenig/lightfold) to [component](https://github.com/reduct/component) and expose them respectively through our unified [reduct](https://github.com/reduct/reduct) package.

So this is just a quick note for double checking that we discuss about the same strategy :)

**Comment by Inkdpixels** [comment]
Yeah you are totally right, I've forgotten that while creating the issues.

**Comment by akoenig** [comment]
no worries :)
